"""add pallet_type to simulation_inputs

Revision ID: 6209c2f547f3
Revises: 9329cdd6ceff
Create Date: 2026-07-19 19:59:49.772455
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '6209c2f547f3'
down_revision: Union[str, None] = '9329cdd6ceff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulation_inputs', sa.Column('pallet_type', sa.String(length=20), server_default='industrial', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulation_inputs', 'pallet_type')
    # ### end Alembic commands ###
