"""initial schema

Revision ID: 9329cdd6ceff
Revises: 
Create Date: 2026-07-15 22:27:29.129646
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '9329cdd6ceff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_grade_refs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=False),
    sa.Column('max_weight_kg', sa.Float(), nullable=False),
    sa.Column('thickness_mm', sa.Float(), nullable=False),
    sa.Column('gsm', sa.Float(), nullable=False),
    sa.Column('cost_per_sqm', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_board_grade_refs_grade'), 'board_grade_refs', ['grade'], unique=True)
    op.create_table('container_specs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('container_type', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('internal_length_m', sa.Float(), nullable=False),
    sa.Column('internal_width_m', sa.Float(), nullable=False),
    sa.Column('internal_height_m', sa.Float(), nullable=False),
    sa.Column('volume_m3', sa.Float(), nullable=False),
    sa.Column('max_payload_kg', sa.Float(), nullable=False),
    sa.Column('tare_kg', sa.Float(), nullable=False),
    sa.Column('freight_factor', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_container_specs_container_type'), 'container_specs', ['container_type'], unique=True)
    op.create_table('package_type_refs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('key', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_package_type_refs_key'), 'package_type_refs', ['key'], unique=True)
    op.create_table('package_weight_refs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('grams', sa.Float(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_package_weight_refs_grams'), 'package_weight_refs', ['grams'], unique=True)
    op.create_table('packaging_material_refs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('key', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('cost_per_sqm', sa.Float(), nullable=False),
    sa.Column('thickness_mm', sa.Float(), nullable=False),
    sa.Column('density_g_cm3', sa.Float(), nullable=False),
    sa.Column('eco_score', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packaging_material_refs_key'), 'packaging_material_refs', ['key'], unique=True)
    op.create_table('pallet_specs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('key', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('length_mm', sa.Float(), nullable=False),
    sa.Column('width_mm', sa.Float(), nullable=False),
    sa.Column('height_mm', sa.Float(), nullable=False),
    sa.Column('max_load_kg', sa.Float(), nullable=False),
    sa.Column('max_stack_height_mm', sa.Float(), nullable=False),
    sa.Column('tare_kg', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pallet_specs_key'), 'pallet_specs', ['key'], unique=True)
    op.create_table('tea_density_refs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tea_type', sa.String(length=50), nullable=False),
    sa.Column('min_density', sa.Float(), nullable=False),
    sa.Column('max_density', sa.Float(), nullable=False),
    sa.Column('typical_density', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tea_density_refs_tea_type'), 'tea_density_refs', ['tea_type'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('simulations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('status', sa.Enum('draft', 'running', 'completed', 'failed', name='simulation_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulations_user_id'), 'simulations', ['user_id'], unique=False)
    op.create_table('carton_configs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('simulation_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('length', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('inner_length', sa.Float(), nullable=False),
    sa.Column('inner_width', sa.Float(), nullable=False),
    sa.Column('inner_height', sa.Float(), nullable=False),
    sa.Column('units_per_carton', sa.Integer(), nullable=False),
    sa.Column('arrangement', sa.String(length=20), nullable=True),
    sa.Column('carton_weight', sa.Float(), nullable=False),
    sa.Column('board_grade', sa.String(length=20), nullable=False),
    sa.Column('board_area_m2', sa.Float(), nullable=True),
    sa.Column('board_cost_per_carton', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('simulation_id')
    )
    op.create_table('comparison_results',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('simulation_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('parameter_name', sa.String(length=100), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('ai_value', sa.Float(), nullable=False),
    sa.Column('improvement_pct', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('driver', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comparison_results_simulation_id'), 'comparison_results', ['simulation_id'], unique=False)
    op.create_table('container_configs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('simulation_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('container_type', sa.Enum('20GP', '40GP', '40HC', name='container_type'), nullable=False),
    sa.Column('pallets_per_container', sa.Integer(), nullable=True),
    sa.Column('pallet_stack', sa.Integer(), nullable=True),
    sa.Column('cartons_per_container', sa.Integer(), nullable=False),
    sa.Column('units_per_container', sa.Integer(), nullable=False),
    sa.Column('capacity_utilization_pct', sa.Float(), nullable=False),
    sa.Column('empty_space_per_container_m3', sa.Float(), nullable=False),
    sa.Column('containers_needed', sa.Integer(), nullable=False),
    sa.Column('total_units_shipped', sa.Integer(), nullable=False),
    sa.Column('utilization_pct', sa.Float(), nullable=False),
    sa.Column('empty_space_total_m3', sa.Float(), nullable=False),
    sa.Column('payload_kg', sa.Float(), nullable=True),
    sa.Column('freight_cost', sa.Float(), nullable=False),
    sa.Column('is_best', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('simulation_id', 'container_type', name='uq_sim_container')
    )
    op.create_index(op.f('ix_container_configs_simulation_id'), 'container_configs', ['simulation_id'], unique=False)
    op.create_table('cost_summary',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('simulation_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('packaging_cost', sa.Float(), nullable=False),
    sa.Column('carton_cost', sa.Float(), nullable=False),
    sa.Column('freight_cost', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('baseline_packaging_cost', sa.Float(), nullable=False),
    sa.Column('baseline_carton_cost', sa.Float(), nullable=False),
    sa.Column('baseline_freight_cost', sa.Float(), nullable=False),
    sa.Column('baseline_total_cost', sa.Float(), nullable=False),
    sa.Column('baseline_assumptions', sa.Text(), nullable=True),
    sa.Column('baseline_is_user_supplied', sa.Boolean(), nullable=False),
    sa.Column('total_savings', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('simulation_id')
    )
    op.create_table('package_options',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('simulation_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('product_volume', sa.Float(), nullable=False),
    sa.Column('length', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('shape', sa.String(length=20), nullable=False),
    sa.Column('material', sa.String(length=20), nullable=False),
    sa.Column('fill_ratio', sa.Float(), nullable=False),
    sa.Column('material_usage', sa.Float(), nullable=False),
    sa.Column('cost_estimate', sa.Float(), nullable=False),
    sa.Column('is_best', sa.Boolean(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_package_options_simulation_id'), 'package_options', ['simulation_id'], unique=False)
    op.create_table('pallet_configs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('simulation_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('cartons_per_layer', sa.Integer(), nullable=False),
    sa.Column('layers', sa.Integer(), nullable=False),
    sa.Column('cartons_per_pallet', sa.Integer(), nullable=False),
    sa.Column('pallet_height', sa.Float(), nullable=False),
    sa.Column('total_weight', sa.Float(), nullable=False),
    sa.Column('layer_pattern', sa.String(length=30), nullable=True),
    sa.Column('footprint_utilization_pct', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('simulation_id')
    )
    op.create_table('simulation_inputs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('simulation_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tea_density', sa.Float(), nullable=False),
    sa.Column('package_weight', sa.Float(), nullable=False),
    sa.Column('shipment_quantity', sa.Integer(), nullable=False),
    sa.Column('shipment_type', sa.Enum('total_weight', 'per_container', name='shipment_type'), nullable=False),
    sa.Column('package_shape', sa.Enum('square', 'round', name='package_shape'), nullable=False),
    sa.Column('packaging_material', sa.Enum('paper', 'plastic', 'metal', name='packaging_material'), nullable=False),
    sa.Column('target_market', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('simulation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulation_inputs')
    op.drop_table('pallet_configs')
    op.drop_index(op.f('ix_package_options_simulation_id'), table_name='package_options')
    op.drop_table('package_options')
    op.drop_table('cost_summary')
    op.drop_index(op.f('ix_container_configs_simulation_id'), table_name='container_configs')
    op.drop_table('container_configs')
    op.drop_index(op.f('ix_comparison_results_simulation_id'), table_name='comparison_results')
    op.drop_table('comparison_results')
    op.drop_table('carton_configs')
    op.drop_index(op.f('ix_simulations_user_id'), table_name='simulations')
    op.drop_table('simulations')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tea_density_refs_tea_type'), table_name='tea_density_refs')
    op.drop_table('tea_density_refs')
    op.drop_index(op.f('ix_pallet_specs_key'), table_name='pallet_specs')
    op.drop_table('pallet_specs')
    op.drop_index(op.f('ix_packaging_material_refs_key'), table_name='packaging_material_refs')
    op.drop_table('packaging_material_refs')
    op.drop_index(op.f('ix_package_weight_refs_grams'), table_name='package_weight_refs')
    op.drop_table('package_weight_refs')
    op.drop_index(op.f('ix_package_type_refs_key'), table_name='package_type_refs')
    op.drop_table('package_type_refs')
    op.drop_index(op.f('ix_container_specs_container_type'), table_name='container_specs')
    op.drop_table('container_specs')
    op.drop_index(op.f('ix_board_grade_refs_grade'), table_name='board_grade_refs')
    op.drop_table('board_grade_refs')
    # ### end Alembic commands ###
